manifest:
  defaults:
    revision: v0.3
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    # Additional modules containing boards/shields/custom code can be listed here as well
    # See https://docs.zephyrproject.org/3.2.0/develop/west/manifest.html#projects
    - name: hitsmaxft
      url-base: https://github.com/hitsmaxft
    - name: urob
      url-base: https://github.com/urob
    - name: carrefinho
      url-base: https://github.com/carrefinho
    - name: caksoylar
      url-base: https://github.com/caksoylar
    # Totem
    - name: GEIGEIGEIST
      url-base: https://github.com/GEIGEIGEIST
  # Urchin keeb
  # - name: duckyb
  #   url-base: https://github.com/duckyb
  projects:
    - name: zmk
      import: app/west.yml
      revision: main
      remote: zmkfirmware
    - name: zmk-keyboard-cornix
      remote: hitsmaxft
      revision: v2.6.3
    - name: zmk-helpers
      remote: urob
      revision: main
    # - name: zmk-rgbled-widget
    #   remote: hitsmaxft
    #   revision: main
    #   clone-depth: 1
    - name: zmk-dongle-display
      remote: hitsmaxft
      revision: main
      clone-depth: 1
    - name: forager-zmk-module
      remote: carrefinho
      revision: main
    - name: zmk-rgbled-widget
      remote: caksoylar
      revision: main
    # - name: urchin-zmk-module
    #   remote: duckyb
    #   revision: main
    # - name: urchin-zmk-module
    #   remote: duckyb
    #   revision: main
    - name: zmk-config-totem
      remote: GEIGEIGEIST
      revision: master
  self:
    path: config
