manifest:
  defaults:
    revision: v0.3
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: hitsmaxft
      url-base: https://github.com/hitsmaxft
    - name: urob
      url-base: https://github.com/urob
    - name: carrefinho
      url-base: https://github.com/carrefinho
    - name: caksoylar
      url-base: https://github.com/caksoylar
    - name: GEIGEIGEIST
      url-base: https://github.com/GEIGEIGEIST
  projects:
    - name: zmk
      import: app/west.yml
      revision: v0.3
      remote: zmkfirmware
    - name: zmk-keyboard-cornix
      remote: hitsmaxft
      revision: main
    - name: zmk-helpers
      remote: urob
      revision: main
    - name: zmk-dongle-display
      remote: hitsmaxft
      revision: main
      clone-depth: 1
    - name: forager-zmk-module
      remote: carrefinho
      revision: main
    - name: zmk-rgbled-widget
      remote: caksoylar
      revision: main
    - name: zmk-config-totem
      remote: GEIGEIGEIST
      revision: master
