
---
events:
  -
    kind: "find_package-v1"
    backtrace:
      - "/zmk-config/zephyr/cmake/modules/zephyr_default.cmake:28 (find_package)"
      - "/zmk-config/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:66 (include)"
      - "/zmk-config/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:92 (include_boilerplate)"
      - "CMakeLists.txt:9 (find_package)"
    name: "ZephyrBuildConfiguration"
    configs:
      -
        filename: "ZephyrBuildConfig.cmake"
        kind: "cmake"
      -
        filename: "zephyrbuild-config.cmake"
        kind: "cmake"
    version_request:
      exact: false
    settings:
      required: "optional"
      quiet: true
      global: false
      policy_scope: false
      bypass_provider: false
      names:
        - "ZephyrBuild"
      search_paths:
        - "/zmk-config/zephyr/../*"
      path_suffixes:
        - ""
      paths:
        CMAKE_FIND_USE_CMAKE_PATH: true
        CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: false
        CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: false
        CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: false
        CMAKE_FIND_USE_INSTALL_PREFIX: true
        CMAKE_FIND_USE_PACKAGE_ROOT_PATH: true
        CMAKE_FIND_USE_CMAKE_PACKAGE_REGISTRY: false
        CMAKE_FIND_USE_SYSTEM_PACKAGE_REGISTRY: false
        CMAKE_FIND_ROOT_PATH_MODE: "BOTH"
    candidates:
      -
        path: "/zmk-config/boards/shields/forager_dongle/CMakeFiles/pkgRedirects/ZephyrBuildConfig.cmake"
        mode: "config"
        reason: "no_exist"
      -
        path: "/zmk-config/boards/shields/forager_dongle/CMakeFiles/pkgRedirects/zephyrbuild-config.cmake"
        mode: "config"
        reason: "no_exist"
      -
        path: "/zmk-config/.git/ZephyrBuildConfig.cmake"
        mode: "config"
        reason: "no_exist"
      -
        path: "/zmk-config/.git/zephyrbuild-config.cmake"
        mode: "config"
        reason: "no_exist"
      -
        path: "/zmk-config/.github/ZephyrBuildConfig.cmake"
        mode: "config"
        reason: "no_exist"
      -
        path: "/zmk-config/.github/zephyrbuild-config.cmake"
        mode: "config"
        reason: "no_exist"
      -
        path: "/zmk-config/config/ZephyrBuildConfig.cmake"
        mode: "config"
        reason: "no_exist"
      -
        path: "/zmk-config/config/zephyrbuild-config.cmake"
        mode: "config"
        reason: "no_exist"
      -
        path: "/zmk-config/zephyr/ZephyrBuildConfig.cmake"
        mode: "config"
        reason: "no_exist"
      -
        path: "/zmk-config/zephyr/zephyrbuild-config.cmake"
        mode: "config"
        reason: "no_exist"
      -
        path: "/zmk-config/zephyr/cmake/ZephyrBuildConfig.cmake"
        mode: "config"
        reason: "no_exist"
      -
        path: "/zmk-config/zephyr/cmake/zephyrbuild-config.cmake"
        mode: "config"
        reason: "no_exist"
      -
        path: "/zmk-config/zmk/ZephyrBuildConfig.cmake"
        mode: "config"
        reason: "no_exist"
      -
        path: "/zmk-config/zmk/zephyrbuild-config.cmake"
        mode: "config"
        reason: "no_exist"
      -
        path: "/zmk-config/zmk-keyboard-cornix/ZephyrBuildConfig.cmake"
        mode: "config"
        reason: "no_exist"
      -
        path: "/zmk-config/zmk-keyboard-cornix/zephyrbuild-config.cmake"
        mode: "config"
        reason: "no_exist"
      -
        path: "/zmk-config/zmk-helpers/ZephyrBuildConfig.cmake"
        mode: "config"
        reason: "no_exist"
      -
        path: "/zmk-config/zmk-helpers/zephyrbuild-config.cmake"
        mode: "config"
        reason: "no_exist"
      -
        path: "/zmk-config/zmk-dongle-display/ZephyrBuildConfig.cmake"
        mode: "config"
        reason: "no_exist"
      -
        path: "/zmk-config/zmk-dongle-display/zephyrbuild-config.cmake"
        mode: "config"
        reason: "no_exist"
      -
        path: "/zmk-config/forager-zmk-module/ZephyrBuildConfig.cmake"
        mode: "config"
        reason: "no_exist"
      -
        path: "/zmk-config/forager-zmk-module/zephyrbuild-config.cmake"
        mode: "config"
        reason: "no_exist"
      -
        path: "/zmk-config/zmk-rgbled-widget/ZephyrBuildConfig.cmake"
        mode: "config"
        reason: "no_exist"
      -
        path: "/zmk-config/zmk-rgbled-widget/zephyrbuild-config.cmake"
        mode: "config"
        reason: "no_exist"
      -
        path: "/zmk-config/urchin-zmk-module/ZephyrBuildConfig.cmake"
        mode: "config"
        reason: "no_exist"
      -
        path: "/zmk-config/urchin-zmk-module/zephyrbuild-config.cmake"
        mode: "config"
        reason: "no_exist"
      -
        path: "/zmk-config/modules/ZephyrBuildConfig.cmake"
        mode: "config"
        reason: "no_exist"
      -
        path: "/zmk-config/modules/zephyrbuild-config.cmake"
        mode: "config"
        reason: "no_exist"
      -
        path: "/zmk-config/firmwares/ZephyrBuildConfig.cmake"
        mode: "config"
        reason: "no_exist"
      -
        path: "/zmk-config/firmwares/zephyrbuild-config.cmake"
        mode: "config"
        reason: "no_exist"
      -
        path: "/zmk-config/builds/ZephyrBuildConfig.cmake"
        mode: "config"
        reason: "no_exist"
      -
        path: "/zmk-config/builds/zephyrbuild-config.cmake"
        mode: "config"
        reason: "no_exist"
      -
        path: "/zmk-config/.opencode/ZephyrBuildConfig.cmake"
        mode: "config"
        reason: "no_exist"
      -
        path: "/zmk-config/.opencode/zephyrbuild-config.cmake"
        mode: "config"
        reason: "no_exist"
      -
        path: "/zmk-config/zmk-config-totem/ZephyrBuildConfig.cmake"
        mode: "config"
        reason: "no_exist"
      -
        path: "/zmk-config/zmk-config-totem/zephyrbuild-config.cmake"
        mode: "config"
        reason: "no_exist"
      -
        path: "/zmk-config/boards/ZephyrBuildConfig.cmake"
        mode: "config"
        reason: "no_exist"
      -
        path: "/zmk-config/boards/zephyrbuild-config.cmake"
        mode: "config"
        reason: "no_exist"
      -
        path: "/zmk-config/.west/ZephyrBuildConfig.cmake"
        mode: "config"
        reason: "no_exist"
      -
        path: "/zmk-config/.west/zephyrbuild-config.cmake"
        mode: "config"
        reason: "no_exist"
    found: null
    search_context:
      ENV{PATH}:
        - "/usr/local/sbin"
        - "/usr/local/bin"
        - "/usr/sbin"
        - "/usr/bin"
        - "/sbin"
        - "/bin"
  -
    kind: "find_package-v1"
    backtrace:
      - "/zmk-config/zephyr/cmake/modules/zephyr_default.cmake:41 (find_package)"
      - "/zmk-config/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:66 (include)"
      - "/zmk-config/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:92 (include_boilerplate)"
      - "CMakeLists.txt:9 (find_package)"
    name: "ZephyrAppConfiguration"
    configs:
      -
        filename: "ZephyrAppConfig.cmake"
        kind: "cmake"
      -
        filename: "zephyrapp-config.cmake"
        kind: "cmake"
    version_request:
      exact: false
    settings:
      required: "optional"
      quiet: true
      global: false
      policy_scope: false
      bypass_provider: false
      names:
        - "ZephyrApp"
      search_paths:
        - "/zmk-config/zmk/app"
      path_suffixes:
        - ""
      paths:
        CMAKE_FIND_USE_CMAKE_PATH: true
        CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: false
        CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: false
        CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: false
        CMAKE_FIND_USE_INSTALL_PREFIX: true
        CMAKE_FIND_USE_PACKAGE_ROOT_PATH: true
        CMAKE_FIND_USE_CMAKE_PACKAGE_REGISTRY: false
        CMAKE_FIND_USE_SYSTEM_PACKAGE_REGISTRY: false
        CMAKE_FIND_ROOT_PATH_MODE: "BOTH"
    candidates:
      -
        path: "/zmk-config/boards/shields/forager_dongle/CMakeFiles/pkgRedirects/ZephyrAppConfig.cmake"
        mode: "config"
        reason: "no_exist"
      -
        path: "/zmk-config/boards/shields/forager_dongle/CMakeFiles/pkgRedirects/zephyrapp-config.cmake"
        mode: "config"
        reason: "no_exist"
      -
        path: "/zmk-config/zmk/app/ZephyrAppConfig.cmake"
        mode: "config"
        reason: "no_exist"
      -
        path: "/zmk-config/zmk/app/zephyrapp-config.cmake"
        mode: "config"
        reason: "no_exist"
    found: null
    search_context:
      ENV{PATH}:
        - "/usr/local/sbin"
        - "/usr/local/bin"
        - "/usr/sbin"
        - "/usr/bin"
        - "/sbin"
        - "/bin"
  -
    kind: "find-v1"
    backtrace:
      - "/zmk-config/zephyr/cmake/modules/ccache.cmake:10 (find_program)"
      - "/zmk-config/zephyr/cmake/modules/zephyr_default.cmake:129 (include)"
      - "/zmk-config/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:66 (include)"
      - "/zmk-config/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:92 (include_boilerplate)"
      - "CMakeLists.txt:9 (find_package)"
    mode: "program"
    variable: "CCACHE_FOUND"
    description: "Path to a program."
    settings:
      SearchFramework: "NEVER"
      SearchAppBundle: "NEVER"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "ccache"
    candidate_directories:
      - "/usr/local/sbin/"
      - "/usr/local/bin/"
      - "/usr/sbin/"
      - "/usr/bin/"
      - "/sbin/"
      - "/bin/"
    searched_directories:
      - "/usr/local/sbin/ccache"
      - "/usr/local/bin/ccache"
      - "/usr/sbin/ccache"
    found: "/usr/bin/ccache"
    search_context:
      ENV{PATH}:
        - "/usr/local/sbin"
        - "/usr/local/bin"
        - "/usr/sbin"
        - "/usr/bin"
        - "/sbin"
        - "/bin"
  -
    kind: "find-v1"
    backtrace:
      - "keymap-module/modules/modules.cmake:95 (find_path)"
      - "/zmk-config/zephyr/cmake/modules/zephyr_module.cmake:130 (include)"
      - "/zmk-config/zephyr/cmake/modules/zephyr_default.cmake:129 (include)"
      - "/zmk-config/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:66 (include)"
      - "/zmk-config/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:92 (include_boilerplate)"
      - "CMakeLists.txt:9 (find_package)"
    mode: "path"
    variable: "BOARD_DIR"
    description: "Path to a file."
    settings:
      SearchFramework: "NEVER"
      SearchAppBundle: "NEVER"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "forager_dongle_defconfig"
    found: false
    search_context:
      ENV{PATH}:
        - "/usr/local/sbin"
        - "/usr/local/bin"
        - "/usr/sbin"
        - "/usr/bin"
        - "/sbin"
        - "/bin"
  -
    kind: "find_package-v1"
    backtrace:
      - "CMakeLists.txt:9 (find_package)"
    name: "Zephyr"
    configs:
      -
        filename: "ZephyrConfig.cmake"
        kind: "cmake"
      -
        filename: "zephyr-config.cmake"
        kind: "cmake"
    version_request:
      exact: false
    settings:
      required: "required_explicit"
      quiet: false
      global: false
      policy_scope: true
      bypass_provider: false
      hints:
        - "../zephyr"
      names:
        - "Zephyr"
      path_suffixes:
        - ""
      paths:
        CMAKE_FIND_USE_CMAKE_PATH: true
        CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
        CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
        CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
        CMAKE_FIND_USE_INSTALL_PREFIX: true
        CMAKE_FIND_USE_PACKAGE_ROOT_PATH: true
        CMAKE_FIND_USE_CMAKE_PACKAGE_REGISTRY: true
        CMAKE_FIND_USE_SYSTEM_PACKAGE_REGISTRY: true
        CMAKE_FIND_ROOT_PATH_MODE: "BOTH"
    candidates:
      -
        path: "/zmk-config/boards/shields/forager_dongle/CMakeFiles/pkgRedirects/ZephyrConfig.cmake"
        mode: "config"
        reason: "no_exist"
      -
        path: "/zmk-config/boards/shields/forager_dongle/CMakeFiles/pkgRedirects/zephyr-config.cmake"
        mode: "config"
        reason: "no_exist"
      -
        path: "/usr/local/ZephyrConfig.cmake"
        mode: "config"
        reason: "no_exist"
      -
        path: "/usr/local/zephyr-config.cmake"
        mode: "config"
        reason: "no_exist"
      -
        path: "/usr/ZephyrConfig.cmake"
        mode: "config"
        reason: "no_exist"
      -
        path: "/usr/zephyr-config.cmake"
        mode: "config"
        reason: "no_exist"
      -
        path: "/ZephyrConfig.cmake"
        mode: "config"
        reason: "no_exist"
      -
        path: "/zephyr-config.cmake"
        mode: "config"
        reason: "no_exist"
    found:
      path: "/zmk-config/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake"
      mode: "config"
      version: "3.5.0"
    search_context:
      ENV{PATH}:
        - "/usr/local/sbin"
        - "/usr/local/bin"
        - "/usr/sbin"
        - "/usr/bin"
        - "/sbin"
        - "/bin"
...
